language: python
python:
  - '3.8.6'

before_install:
  - python -m pip install --upgrade pip

branches:
  only:
    - staging

addons:
  chrome: stable

install:
  - pip install -r requirements.txt

env:
  - ENV=production

services:
  - postgresql

before_script:
  - wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /usr/local/bin/chromedriver
  - export PATH="$PATH:/usr/local/bin/chromedriver"


script:
  - python manage.py test
