# Generated by Django 3.2 on 2021-05-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0002_auto_20210503_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.categoryproduct'),
        ),
    ]
